[package]
name = "cargo-debstatus"
version = "0.2.0"
description = "cargo-tree for debian packaging"
authors = ["kpcyrd <git@rxv.cc>",
           "Steven Fackler <sfackler@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/cargo-debstatus"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
cargo = "0.32.0"
env_logger = "0.6"
failure = "0.1"
structopt = "0.2.10"
petgraph = "0.4"
semver = "0.9.0"
colored = "1.6.1"
#postgres = { version="0.15.2", features=["with-native-tls"] }
postgres = "0.15.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dirs = "1.0"
